nginx:
  image: nginx:alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # - ~/Sites/:/Sites/:rw
    - ./wwwroot/:/var/www/html/:rw
    - ./Config/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./Config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./Logs/nginx/:/var/log/nginx/:rw
  links:
    - php-fpm:fpm
  container_name: nginx
  restart: always

php-fpm:
  build: ./Config/php
  expose:
    - "9000"
  volumes:
    - ./wwwroot/:/var/www/html/:rw
    - ./Config/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./Config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    - ./Logs/php-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
    - redis:redis
    - memcached:memcached
    - mongo:mongo
  container_name: php-fpm
  restart: always

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./Config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    - ./Databases/mysql/:/var/lib/mysql/:rw
    - ./Logs/mysql/:/var/log/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "l9851223"
  container_name: mysql
  restart: always

redis:
  image: redis
  command: redis-server /usr/local/etc/redis.conf
  ports:
    - "6379:6379"
  volumes:
    - ./Databases/redis/:/usr/local/redis/:rw
    - ./Config/redis/redis.conf:/usr/local/etc/redis.conf:ro
  container_name: redis
  restart: always

mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - ./Config/mongodb/mongod.conf:/etc/mongod.conf:ro
    - ./Databases/mongodb/:/data/:rw
    - ./Logs/mongodb/:/var/log/mongodb/:rw
  container_name: mongodb
  restart: always

memcached:
  image: memcached
  ports:
    - "11211:11211"
  container_name: memcached
  restart: always

java-maven-tomcat:
  # 免构建镜像，未修改构建文件下等同于构建本地镜像，如使用本地 build 需注释此行并关闭 build 注释。
  # image: registry.cn-hangzhou.aliyuncs.com/springjk/java-maven-tomcat
  # 构建本地镜像
  build: ./java-maven-tomcat
  links:
    - mysql
  # 将容器的8080端口绑定到宿主机的80端口
  ports:
    - "8080:8080"
  # java-maven-tomcat 容器启动后的运行命令
  command: "bash /tmp/build.sh"
  volumes:
    # 挂载 Maven 的缓存目录
    - ./Databases/maven:/usr/share/maven/ref/repository
    # 挂载 Tomcat 的 log 目录
    - ./Logs/tomcat:/usr/local/tomcat/logs
    # 挂载 JAVA 源代码目录
    - ./CodeJava:/tmp/code
  restart: always
